# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/interview',
                'doc_host': 'https://grey1227.github.io',
                'git_url': 'https://github.com/grey1227/interview',
                'lib_path': 'interview'},
  'syms': {'interview.core': {'interview.core.foo': ('core.html#foo', 'interview/core.py')}}}
